### ISSUE TITLE
traffic between WAG and ASE is not https but http

### ISSUE THREAD

**Issue by olafsurewaard** [AvyanConsultingCorp/pci-paas-webapp-ase-sqldb-appgateway-keyvault-oms#1]
###The reference architecture describes a situation where ssl is used end to end, also for traffic between Web Application Gateway and Application Service Environment. 
However when I look at the arm template I notice that this traffic is still defined as http instead of https:

In pci-paas-webapp-ase-sqldb-appgateway-keyvault-oms/nested/appgatewaydeploy.json I notice that appGatewayBackendHttpSettings instead of the also defined appGatewayBackendHttpsSettings is used. 
As a result ssl will be offloaded, but traffic between WAG and ASE will be http in stead of https.

{
	"Name": "httpsRule",
	"properties": {
	"RuleType": "Basic",
	"httpListener": {
	"id": "[concat(variables('applicationGatewayId'), '/httpListeners/appGatewayHttpsListener')]"
	},
	"backendAddressPool": {
	"id": "[concat(variables('applicationGatewayId'), '/backendAddressPools/appGatewayBackendPool')]"
	},
	"backendHttpSettings": {
	"id": "[concat(variables('applicationGatewayId'), '/backendHttpSettingsCollection/appGatewayBackendHttpSettings')]"
	}
	}
	}
I have been testing with using appGatewayBackendHttp**s**Setting, but seem not to get it to work. I receive 502 errors when accessing a web app in the Application Service Environment

We are using multisite listeners with hostnames in different domains than the domain configured at the ASE ILB.

Any Thoughts?

**Comment by consultguru** [comment]
As indicated in the email, there seems to be a bug in the ASE implementation of SSL especially if there's an AppGateway a layer above. We are working with Microsoft to understand and figure out the workarounds. Some of them are
1) Change ASE from an ILB to a public facing configuration. Download and *.azurewebsites.net wildcard cert. Create a custom probe that points back to the azurewebsites.net address of the app service using that cert on the back end HTTPS
2) Lock down the traffic by adding NSG rules. However, this may not prevent man-in-middle attacks
3) Lock down the traffic by whitelisting Appgateway IP in the web.config. Again, however, this may not prevent man-in-middle attacks

We will provide an update on trying out and getting it reviewed.

**Comment by consultguru** [comment]
Hi @olafsurewaard 

We have released an update to encrypt traffic between AppGateway(WAF) and App Service Environment. 

Please try that out and let us know.

We would be closing this issue.
